plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
    }
}

project.ext {
    jmeVer = '3.8.1-stable'
    boostVer = 'dd2f4b856d'
    computeVer = '2.0.1'
}

dependencies {
    implementation project(":RenthylCore")
    implementation project(":JMECompute")
    //implementation "com.github.codex128:JMECompute:$computeVer"
    implementation "org.jmonkeyengine:jme3-core:$jmeVer"
    implementation "org.jmonkeyengine:jme3-lwjgl3:$jmeVer"
    implementation "org.jmonkeyengine:jme3-effects:$jmeVer"
    implementation "com.github.codex128:Boost:$boostVer"
}

tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allJava
    archiveClassifier = 'sources'
}

tasks.register('javadocJar', Jar) {
    from javadoc
    archiveClassifier = 'javadoc'
}

publishing {
    publications {
        LibraryPublication(MavenPublication) {
            from components.java
            artifact sourcesJar
            artifact javadocJar
        }
    }
}
